apiVersion: v1
kind: PersistentVolume
metadata:
  name: jsppv
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce # Or ReadOnlyMany, ReadWriteMany if applicable
  storageClassName: standard
  hostPath:
    path: /data/jspdb
  persistentVolumeReclaimPolicy: Retain # Or Recycle, Delete
