apiVersion: apps/v1
kind: Deployment
metadata:
  name: jspweb
  labels:
    app: jspweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jspweb
  template:
    metadata:
      labels:
        app: jspweb
    spec:
      containers:
      - name: jspweb
        image: kubesk071/jspapp:k8s-v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-host

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: jspdb-secret
              key: username

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: jspdb-secret
              key: password



---

apiVersion: v1
kind: Service
metadata:
  name: jspweb-service
spec:
  type: NodePort
  selector:
    app: jspweb
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30005
